version: "3.9"
networks:
  chainnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  node_a:
    build: .
    container_name: node_a
    ports: ["8001:8000"]
    environment:
      - NODE_ID=node_a
      - NODE_IP=172.28.0.11
      - PRIVATE_KEY_PATH=/keys/priv.asc
    volumes:
      - ./keys/node_a_priv.asc:/keys/priv.asc:ro
    networks:
      chainnet:
        ipv4_address: 172.28.0.11

  node_b:
    build: .
    container_name: node_b
    ports: ["8002:8000"]
    environment:
      - NODE_ID=node_b
      - NODE_IP=172.28.0.12
      - PRIVATE_KEY_PATH=/keys/priv.asc
    volumes:
      - ./keys/node_b_priv.asc:/keys/priv.asc:ro
    networks:
      chainnet:
        ipv4_address: 172.28.0.12

  node_c:
    build: .
    container_name: node_c
    ports: ["8003:8000"]
    environment:
      - NODE_ID=node_c
      - NODE_IP=172.28.0.13
      - PRIVATE_KEY_PATH=/keys/priv.asc
    volumes:
      - ./keys/node_c_priv.asc:/keys/priv.asc:ro
    networks:
      chainnet:
        ipv4_address: 172.28.0.13
